services:
  geth-sepolia:
    container_name: geth-sepolia
    image: ethereum/client-go:stable
    command:
      --sepolia
      --ws
      --ws.addr=0.0.0.0
      --ws.origins="*"
      --datadir=/data
      --http
      --http.addr=0.0.0.0
      --http.api="eth,net,engine,admin,txpool"
      --http.corsdomain="*"
      --http.vhosts="*"
      --authrpc.addr=0.0.0.0
      --authrpc.vhosts="*"
      --authrpc.jwtsecret=/jwt/jwtsecret
      --bootnodes enode://ec66ddcf1a974950bd4c782789a7e04f8aa7110a72569b6e65fcd51e937e74eed303b1ea734e4d19cfaec9fbff9b6ee65bf31dcb50ba79acce9dd63a6aca61c7@52.14.151.177:30303
    volumes:
      - '/home/geth-data:/data'
      - '/home/jwt:/jwt'
    ports:
      - '31303:30303'
      - '31545:8545' #json-rpc endpoint
      - '31546:8546' #wss endpoint
      - '31547:8547'
      - '31551:8551' #auth endpoint
  prysm-sepolia:
    container_name: prysm-sepolia
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    command: --datadir=/data
      --jwt-secret=/jwt/jwtsecret
      --rpc-host=0.0.0.0
      --grpc-gateway-host=0.0.0.0
      --monitoring-host=0.0.0.0
      --execution-endpoint=http://geth-sepolia:8551
      --genesis-beacon-api-url=https://sepolia.beaconstate.info
      --checkpoint-sync-url=https://sepolia.beaconstate.info
      --enable-experimental-backfill=true
      --sepolia --accept-terms-of-use
    volumes:
      - '/home/prysm-data:/data'
      - '/home/jwt:/jwt'
    ports:
      - '31400:4000'
      - '31500:3500' #beacon endpoint
      - '31300:13000'
      - '31200:12000/udp'